
import "dart:io";

void main() async {
  final directories = ["../../lib/view/manager", "../../lib/view/sale"];
  for (var dir in directories) {
    final dirInfo = Directory(dir);
    if (!dirInfo.existsSync()) continue;
    
    for (var entity in dirInfo.listSync()) {
      if (entity is File && entity.path.endsWith(".dart")) {
        final lines = await entity.readAsLines();
        List<String> newLines = [];
        bool skip = false;
        
        for (var line in lines) {
          if (line.startsWith("void main() {")) {
            skip = true;
          }
          if (skip && line == "}") {
            skip = false;
            continue;
          }
          if (skip) continue;
          
          if (line.startsWith("class FigmaToCodeApp extends StatelessWidget {")) {
            skip = true;
          }
          if (skip && line == "}") {
            skip = false;
            continue;
          }
          if (skip) continue;
          
          if (line.contains("runApp(const FigmaToCodeApp());")) continue;
          if (line.contains("// Generated by:")) continue;
          
          newLines.add(line);
        }
        
        // Remove trailing or extra spaces
        await entity.writeAsString(newLines.join("\n"));
        print("Cleaned ${entity.path}");
      }
    }
  }
}

